name: time2graph
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2025.11.4
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=24.2
  - pthread-stubs=0.3
  - python=3.8.20
  - readline=8.3
  - setuptools=75.1.0
  - sqlite=3.51.0
  - tk=8.6.15
  - wheel=0.44.0
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - argparse==1.4.0
      - cython==3.2.1
      - deepwalk==1.0.3
      - dill==0.4.0
      - filelock==3.16.1
      - fsspec==2025.3.0
      - futures==3.0.5
      - gensim==4.3.3
      - jinja2==3.1.6
      - joblib==1.4.2
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - networkx==3.1
      - numpy==1.19.5
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - pandas==1.1.5
      - pillow==10.4.0
      - psutil==7.1.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - scikit-learn==0.23.2
      - scipy==1.10.1
      - six==1.17.0
      - smart-open==7.3.1
      - sympy==1.13.3
      - threadpoolctl==3.5.0
      - torch==2.4.1
      - torchaudio==2.4.1
      - torchvision==0.19.1
      - triton==3.0.0
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - wrapt==2.0.1
      - xgboost==0.80
prefix: /home/wangjun/miniconda3/envs/time2graph
